import { Exclude } from 'class-transformer';
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';

export enum IdentityProgress {
  PENDING = 'pending',
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
}

export enum IdentityRole {
  OWNER = 'owner',
  ADMIN = 'admin',
  MEMBER = 'member',
}

@Entity('identities')
@Index('idx_tenant_id_email', ['tenantId', 'email'], { unique: true })
export class Identities {
  // Generated by the app (uuidv7) before the org-service call, not by Postgres.
  @PrimaryColumn({ type: 'uuid' })
  id!: string;

  @Column({
    name: 'role',
    type: 'enum',
    enum: IdentityRole,
    default: IdentityRole.MEMBER,
  })
  role!: IdentityRole;

  // uuid, matching tenant_refs.tenant_id.
  @Column({ name: 'tenant_id', type: 'uuid', nullable: false })
  tenantId!: string;

  // The single answer to "may this identity authenticate". isActive removed.
  @Column({
    name: 'status',
    type: 'enum',
    enum: IdentityProgress,
    default: IdentityProgress.PENDING,
  })
  status!: IdentityProgress;

  @Column({ name: 'email', type: 'varchar', length: 255, nullable: false })
  email!: string;

  @Column({ name: 'email_verified_at', type: 'timestamptz', nullable: true })
  emailVerifiedAt?: Date;

  @Column({ name: 'password_hash', type: 'varchar', nullable: false })
  @Exclude()
  passwordHash!: string;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @DeleteDateColumn({ name: 'deleted_at', type: 'timestamptz' })
  deletedAt?: Date;
}
